### PR TITLE
Adds auth workflow diagram images

### PR DESCRIPTION
**Pull request by ttomsu**
@skim1420 @duftler @jtk54 FYI

### CODE REVIEW

**Comment by ttomsu** [comment]
Published: https://ttomsu.github.io/documentation/security/workflow/

**Review by skim1420 — COMMENTED** [review]
For diagrams, is it possible to use markdown-based (or text-based) diagram renderers? Not sure if it works with jekyll.

**Comment by duftler** [comment]
Renders nicely on phone.

**Comment by ttomsu** [comment]
Here's what client-side rendered sequence diagrams look like:
https://ttomsu.github.io/documentation/security/workflow/

They're not as pretty, but potentially more maintainable.

**Pull request merged**
